$(window).load(function(){setTimeout(function(){$(".loading-overlay").addClass("animated")},500);setTimeout(function(){$(".loading-overlay").addClass("hidden")},900);setTimeout(function(){animated_home_left()},1200);setTimeout(function(){animated_home_box()},1700);var spot=Math.floor(Math.random()*2);if(spot==0){$(".peter").addClass("peter1")}else{$(".peter").addClass("peter2")}});$(document).ready(function(){fixe_color();home_text();height_min_win(".home-box-outer");height_min_win(".peter");margin_win(".section-top-right");center_margin(".home-box");center_margin(".section-top-text");lines_height();$('.nav ul').onePageNav();window.addEventListener('scroll',function(){fixe_color();home_text();center_margin(".home-box");center_margin(".section-top-text")});window.addEventListener('resize',function(){height_min_win(".home-box-outer");height_min_win(".peter");margin_win(".section-top-right");lines_height();center_margin(".home-box");center_margin(".section-top-text")});imghero=document.querySelector('.peter__back--mover');win={width:window.innerWidth,height:window.innerHeight};window.addEventListener('mousemove',throttle(function(ev){var xVal=-1/(win.height/2)*ev.clientY+1,yVal=1/(win.width/2)*ev.clientX-1,transX=20/(win.width)*ev.clientX-10,transY=20/(win.height)*ev.clientY-10,transZ=100/(win.height)*ev.clientY-50;imghero.style.WebkitTransform='perspective(1000px) translate3d('+transX+'px,'+transY+'px,'+transZ+'px) rotate3d('+xVal+','+yVal+',0,2deg)';imghero.style.transform='perspective(1000px) translate3d('+transX+'px,'+transY+'px,'+transZ+'px) rotate3d('+xVal+','+yVal+',0,2deg)'},50));var getMax=function(){return $('html').height()-$(window).height()};var getValue=function(){return $(window).scrollTop()};var progressBar=$('.progress-bar'),max=getMax(),value,width;var getWidth=function(){value=getValue();width=(value/max)*100;width=width+'%';return width};var setWidth=function(){progressBar.css({width:getWidth()})};setWidth();$(document).on('scroll',setWidth);$(window).on('resize',function(){max=getMax();setWidth()});$(".form-wrap input, .form-wrap textarea").on("input",function(){if($(this).val().length>1){$(this).parent().addClass("filled")}else{$(this).parent().removeClass("filled")}});$(".menu-toggle, .menu-close").on("click",function(){if($(".nav").hasClass("open")){setTimeout(function(){$(".nav").removeClass("open")},1000)
    $(".nav-content").removeClass("open")}else{$(".nav").addClass("open");setTimeout(function(){$(".nav-content").addClass("open")},1000)}
    return!1});$(document).click(function(event){if(!$(event.target).closest('.nav').length){if($('.nav').hasClass("open")){setTimeout(function(){$(".nav").removeClass("open")},1000)
    $(".nav-content").removeClass("open")}}});$(".home-box-inner a").click(function(){$('html,body').animate({scrollTop:$("#contact").offset().top},2000);return!1});$(".logo-icon").click(function(){$('html,body').animate({scrollTop:$("#top").offset().top},2000);return!1});$(".nav-col ul li a").click(function(){setTimeout(function(){$(".nav").removeClass("open")},500);$(".nav-content").removeClass("open");var target=$(this.hash);target=target.length?target:$('[name='+this.hash.slice(1)+']');if(target.length){$('html, body').animate({scrollTop:target.offset().top},2000);return!1}});$(".scroll").click(function(){var target=$(this.hash);target=target.length?target:$('[name='+this.hash.slice(1)+']');if(target.length){$('html, body').animate({scrollTop:target.offset().top},2000);return!1}});$('body,html').bind('scroll mousedown wheel DOMMouseScroll mousewheel keyup touchmove',function(e){if(e.which>0||e.type=="mousedown"||e.type=="mousewheel"||e.type=="touchmove"){$("html,body").stop()}});$(".form form").submit(function(event){event.preventDefault();var form=$('#form-ajax');var formData=$(form).serialize();$(".form-wrap input, .form-wrap textarea").each(function(){if($(this).val().length>1){$(this).parent().removeClass("error").addClass("ok")}else{$(this).parent().removeClass("ok").addClass("error")}});$.ajax({type:'POST',url:$(form).attr('action'),data:formData}).done(function(response){$(".form input[type='submit']").val("Wysłano ;)").addClass("send").prop('disabled',!0)}).fail(function(data){if(data.responseText!==''){console.log(data.responseText)}else{}})})});function throttle(fn,delay){var allowSample=!0;return function(e){if(allowSample){allowSample=!1;setTimeout(function(){allowSample=!0},delay);fn(e)}}}
function home_text(){var max_scroll=$(".section-top-right").height()-$(window).height();if($(".section-top-text").hasClass("fixed")){if($(window).scrollTop()>max_scroll){$(".section-top-text").removeClass("fixed")}else{$(".section-top-text").css({top:$(window).scrollTop()})}}else{if($(window).scrollTop()<max_scroll){$(".section-top-text").addClass("fixed").css({top:$(window).scrollTop()})}else{$(".section-top-text").css({top:max_scroll})}}
    var scroll_text=$(window).height()/2;if($(window).width()<768){scroll_text=50}
    if($(window).scrollTop()>scroll_text){$(".change-text .first").addClass("hidden");$(".change-text .second").removeClass("hidden")}else{$(".change-text .first").removeClass("hidden");$(".change-text .second").addClass("hidden")}}
function fixe_color(){if($(window).scrollTop()>40){$(".logo-fixed").addClass("visible")}else{$(".logo-fixed").removeClass("visible")}
    if($(window).scrollTop()>$(".white-box").offset().top-40){$(".menu-toggle").addClass("black");$(".logo-fixed").addClass("black-mobile")}else if($(window).scrollTop()<$(".white-box").offset().top-40){$(".menu-toggle").removeClass("black");$(".logo-fixed").removeClass("black-mobile")}
    if($(window).scrollTop()>$(".boxs-black").offset().top-40){$(".menu-toggle").removeClass("black");$(".logo-fixed").removeClass("black-mobile")}
    if($(window).scrollTop()>$(".box-white").offset().top-40){$(".logo-fixed").removeClass("white");$(".menu-toggle").addClass("black")}else{$(".logo-fixed").addClass("white")}}
function animated_home_box(){$(".line1").addClass("animated");setTimeout(function(){$(".line2").addClass("animated")},400);setTimeout(function(){$(".line3").addClass("animated")},800);setTimeout(function(){$(".line4").addClass("animated")},1200);setTimeout(function(){$(".line5").addClass("animated")},1600);setTimeout(function(){$(".home-box-inner").addClass("animated")},2000)}
function animated_home_left(){setTimeout(function(){$(".section-top-text").addClass("animated")},300)}
function height_min_win(box){var box_=$(box);var height=$(window).height()
    if(detectmob()){height=window.screen.availHeight}
    box_.css("min-height",height)}
function detectmob(){if(window.innerWidth<=800&&window.innerHeight<=600){return!0}else{return!1}}
function center_margin(box){var box_=$(box);var height=($(window).height()-$(box).outerHeight())/2;box_.css("margin-top",height)}
function lines_height(){var height=$(".box-white").offset().top;setTimeout(function(){$(".grid1,.grid2,.grid3,.grid4,.grid5").css("height",height)},100)}
function margin_win(box){var box_=$(box);var height=$(window).height();if(detectmob()){height=window.screen.availHeight}
    box_.css("margin-top",height)}